id: P010581
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W2CZ5665
  title: མངོན་རྟོགས་རྒྱན་གྱི་མཆན་འགྲེལ
  author: ''
  volumes:
    857b306890b84653ab3327f70b779cd1:
      image_group_id: I1KG413
      title: ''
      volume_number: 1
      total_pages: 92
      base_file: v001.txt
